In [1]:
!pip install newsapi-python


In [ ]:
pip install feedparser

In [ ]:
pip install eikon

In [2]:
import nltk,bs4
import eikon as ek
from bs4 import BeautifulSoup
from nltk import word_tokenize
import configparser as cp

ModuleNotFoundError: No module named 'eikon'

In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


In [ ]:
ek.__version__

'1.1.18'

In [ ]:
nltk.__version__

'3.8.1'

In [ ]:
bs4.__version__

'4.12.3'

In [ ]:
cfg=cp.ConfigParser()
cfg.read('eikon.cfg')

[]

In [ ]:
pip install beautifulsoup4 requests


In [ ]:
pip install yfinance


In [ ]:
pip install newsapi-python


In [ ]:
pip install nytimesarticle


  Preparing metadata (setup.py) ... done
  Created wheel for nytimesarticle: filename=nytimesarticle-0.1.0-py3-none-any.whl size=3976 sha256=be369c243a7deff211314c803deb27bc6e5244f7b3508fa73135dd6337ad6a8b
  Stored in directory: /root/.cache/pip/wheels/0d/47/e5/56fb157c51d0f441375c79fb179283e7c080fd274d4dae601a
Successfully built nytimesarticle


In [ ]:
pip install newsapi-python


In [6]:
import requests
from bs4 import BeautifulSoup
import csv
def extract_articles_from_page(page_number):
    url = f"https://www.ft.com/search?q=amazon+Inc.&page={page_number}"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    articles = []
    for article in soup.find_all('div', class_='o-teaser'):
        title_tag = article.find('a', class_='js-teaser-heading-link')
        date_tag = article.find('time', class_='o-teaser__timestamp-date')

        if title_tag and date_tag:
            title = title_tag.get_text(strip=True)
            date = date_tag.get_text(strip=True)
            articles.append((date, title))

    return articles

all_articles = []
for page in range(1, 300):
    print(f"Scraping page {page}")
    articles = extract_articles_from_page(page)
    all_articles.extend(articles)

# Write the data to a CSV file
with open('amazone_news_articles.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    # Write the header
    writer.writerow(['Date', 'Title'])
    # Write the articles
    for article in all_articles:
        writer.writerow(article)

print("Data has been written to apple_news_articles.csv")


Scraping page 1
Scraping page 2
Scraping page 3
Scraping page 4
Scraping page 5
Scraping page 6
Scraping page 7
Scraping page 8
Scraping page 9
Scraping page 10
Scraping page 11
Scraping page 12
Scraping page 13
Scraping page 14
Scraping page 15
Scraping page 16
Scraping page 17
Scraping page 18
Scraping page 19
Scraping page 20
Scraping page 21
Scraping page 22
Scraping page 23
Scraping page 24
Scraping page 25
Scraping page 26
Scraping page 27
Scraping page 28
Scraping page 29
Scraping page 30
Scraping page 31
Scraping page 32
Scraping page 33
Scraping page 34
Scraping page 35
Scraping page 36
Scraping page 37
Scraping page 38
Scraping page 39
Scraping page 40
Scraping page 41
Scraping page 42
Scraping page 43
Scraping page 44
Scraping page 45
Scraping page 46
Scraping page 47
Scraping page 48
Scraping page 49
Scraping page 50
Scraping page 51
Scraping page 52
Scraping page 53
Scraping page 54
Scraping page 55
Scraping page 56
Scraping page 57
Scraping page 58
Scraping page 59
Scrapi

In [7]:
import pandas as pd

# Load the CSV file
file_path = '/content/amazone_news_articles.csv'  # Replace with your file path

# Read the data from the CSV file
df = pd.read_csv(file_path)

# Convert the 'date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Sort the DataFrame by 'date' in descending order
df_sorted = df.sort_values(by='Date', ascending=False)

# Save the sorted DataFrame back to a CSV file
output_file_path = '/content/amazone_news_articles.csv'  # Replace with your output file path
df_sorted.to_csv(output_file_path, index=False)

print("Data sorted and saved successfully.")


Data sorted and saved successfully.


In [8]:
pip install yfinance

In [9]:
import yfinance as yf


In [10]:
AMZN= yf.Ticker("AMZN")

In [11]:
AMZN.history(period="1mo")

Open        High         Low       Close  \
Date                                                                        
2024-05-20 00:00:00-04:00  184.339996  186.669998  183.279999  183.539993   
2024-05-21 00:00:00-04:00  182.300003  183.259995  180.750000  183.149994   
2024-05-22 00:00:00-04:00  183.880005  185.220001  181.970001  183.130005   
2024-05-23 00:00:00-04:00  183.660004  184.759995  180.080002  181.050003   
2024-05-24 00:00:00-04:00  181.649994  182.440002  180.300003  180.750000   
2024-05-28 00:00:00-04:00  179.929993  182.240005  179.490005  182.149994   
2024-05-29 00:00:00-04:00  181.699997  184.080002  181.550003  182.020004   
2024-05-30 00:00:00-04:00  181.309998  181.339996  178.360001  179.320007   
2024-05-31 00:00:00-04:00  178.300003  179.210007  173.869995  176.440002   
2024-06-03 00:00:00-04:00  177.699997  178.699997  175.919998  178.339996   
2024-06-04 00:00:00-04:00  177.639999  179.820007  176.440002  179.339996   
2024-06-05 00:00:00-04:00  180.100006  181.500000  178.750000  181.279999   
2024-06-06 00:00:00-04:00  181.750000  185.000000  181.490005  185.000000   
2024-06-07 00:00:00-04:00  184.899994  186.289993  183.360001  184.300003   
2024-06-10 00:00:00-04:00  184.070007  187.229996  183.789993  187.059998   
2024-06-11 00:00:00-04:00  187.059998  187.770004  184.539993  187.229996   
2024-06-12 00:00:00-04:00  188.020004  188.350006  185.429993  186.889999   
2024-06-13 00:00:00-04:00  186.089996  187.669998  182.669998  183.830002   
2024-06-14 00:00:00-04:00  183.080002  183.720001  182.229996  183.660004   
2024-06-17 00:00:00-04:00  182.520004  185.000000  181.220001  184.059998   
2024-06-18 00:00:00-04:00  183.740005  184.289993  181.429993  182.809998   

                             Volume  Dividends  Stock Splits  
Date                                                          
2024-05-20 00:00:00-04:00  30511800        0.0           0.0  
2024-05-21 00:00:00-04:00  50839100        0.0           0.0  
2024-05-22 00:00:00-04:00  28148800        0.0           0.0  
2024-05-23 00:00:00-04:00  33670200        0.0           0.0  
2024-05-24 00:00:00-04:00  27434100        0.0           0.0  
2024-05-28 00:00:00-04:00  29927000        0.0           0.0  
2024-05-29 00:00:00-04:00  32009300        0.0           0.0  
2024-05-30 00:00:00-04:00  29249200        0.0           0.0  
2024-05-31 00:00:00-04:00  58903900        0.0           0.0  
2024-06-03 00:00:00-04:00  30786600        0.0           0.0  
2024-06-04 00:00:00-04:00  27198400        0.0           0.0  
2024-06-05 00:00:00-04:00  32116400        0.0           0.0  
2024-06-06 00:00:00-04:00  31371200        0.0           0.0  
2024-06-07 00:00:00-04:00  28021500        0.0           0.0  
2024-06-10 00:00:00-04:00  34494500        0.0           0.0  
2024-06-11 00:00:00-04:00  27265100        0.0           0.0  
2024-06-12 00:00:00-04:00  33984200        0.0           0.0  
2024-06-13 00:00:00-04:00  39721500        0.0           0.0  
2024-06-14 00:00:00-04:00  25456400        0.0           0.0  
2024-06-17 00:00:00-04:00  35601900        0.0           0.0  
2024-06-18 00:00:00-04:00  36624600        0.0           0.0

In [12]:
import yfinance as yf
from datetime import datetime, timedelta

# Set the end date to today's date
end_date = datetime.today().strftime('%Y-%m-%d')

# Set the start date to 10/11/2019
start_date = '2019-10-11'

# Get historical stock data for AMZN from start_date to end_date
data = yf.download('AMZN', start=start_date, end=end_date)

# Save the data to a CSV file
output_file = 'amazon_stock.csv'
data.to_csv(output_file)

print(f"Data saved to {output_file}")


[*********************100%%**********************]  1 of 1 completed

Data saved to amazon_stock.csv


In [13]:
import pandas as pd

# Provide the paths of CSV files in Google Colab
file1_path = '/content/amazone_news_articles.csv'
file2_path = '/content/amazon_stock.csv'

# Load data from both files
data1 = pd.read_csv(file1_path)
data2 = pd.read_csv(file2_path)

# Convert 'Date' column to datetime format
data1['Date'] = pd.to_datetime(data1['Date'])
data2['Date'] = pd.to_datetime(data2['Date'])

# Initialize an empty list to store labels
labels = []

# Iterate through dates in file1 and find next day's closing price in file2
for date in data1['Date']:
    # Find the index of the current date in file2
    idx = data2[data2['Date'] == date].index
    if len(idx) > 0 and idx[0] < len(data2) - 1:
        next_day_close = data2.loc[idx[0] + 1, 'Close']
        today_close = data2.loc[idx[0], 'Close']
        # Label 1 if next day's price is higher, otherwise 0
        label = 1 if next_day_close > today_close else 0
    else:
        # If next day's data is not available, assign label as -1
        label = -1
    labels.append(label)

# Add 'Label' column to file1
data1['Label'] = labels

# Save the updated data to the same file
data1.to_csv(file1_path, index=False)

print("Labels added to file1.csv.")


Labels added to file1.csv.


In [14]:
import pandas as pd

# Provide the path of the CSV file containing the 'Label' column
file_path = '/content/amazone_news_articles.csv'

# Load data from the file
data = pd.read_csv(file_path)

# Remove rows where 'Label' column contains -1
data = data[data['Label'] != -1]

# Save the updated data to the same file
data.to_csv(file_path, index=False)

print("Rows with Label -1 removed from the file.")


Rows with Label -1 removed from the file.


In [15]:
import pandas as pd

# Provide the path of the CSV file containing the 'Label' column
file_path = '/content/amazone_news_articles.csv'

# Load data from the file
data = pd.read_csv(file_path)

# Count the number of zeros and ones in the 'Label' column
zeros_count = (data['Label'] == 0).sum()
ones_count = (data['Label'] == 1).sum()

print(f"Number of zeros: {zeros_count}")
print(f"Number of ones : {ones_count}")


Number of zeros: 441
Number of ones : 451


In [16]:
import pandas as pd

# Provide the path of the CSV file
file_path = '/content/amazone_news_articles.csv'

# Load data from the CSV file
df = pd.read_csv(file_path, encoding="ISO-8859-1")


In [17]:
df.head()

Date                                              Title  Label
0  2024-06-13               How AI may become the new offshoring      0
1  2024-06-12                        Apple’s belated AI gambit      0
2  2024-06-10  Can Apple catch up with its rivals in the AI r...      1
3  2024-06-10  Apple partners with OpenAI to roll out new art...      1
4  2024-06-07        You can’t call a company Scorpio Bastardo      1

In [18]:
from sklearn.model_selection import train_test_split

# Assuming df contains your dataset

# Splitting the data into train and test sets (80:20 ratio)
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# Print the sizes of train and test sets
print("Train set size:", len(train_df))
print("Test set size:", len(test_df))


Train set size: 713
Test set size: 179


In [19]:
import pandas as pd

# Assuming 'train' is your DataFrame containing the training dataset

# Removing punctuations from the 'Title' column
train_df['Title'] = train_df['Title'].str.replace("[^a-zA-Z]", " ", regex=True)

# Renaming column names for ease of access (if necessary)
# list1 = [i for i in range(25)]
# new_Index = [str(i) for i in list1]
# data.columns = new_Index

# Displaying the modified DataFrame
train_df.head()


Date                                              Title  Label
331  2022-04-13  Activist investor in Peloton takes aim at new ...      0
734  2020-08-28  Apple and Tesla turn spotlight back on stock s...      1
382  2022-01-20  US Senate committee advances bill to tame Big ...      0
705  2020-10-05            How Walmart   s UK invasion fizzled out      0
814  2020-06-04                      Snap makes Trump posts vanish      1

In [20]:
# Assuming 'train' is your DataFrame containing the training dataset

# Convert the 'Title' column to lowercase
train_df['Title'] = train_df['Title'].str.lower()

# Displaying the modified DataFrame
train_df.head()


Date                                              Title  Label
331  2022-04-13  activist investor in peloton takes aim at new ...      0
734  2020-08-28  apple and tesla turn spotlight back on stock s...      1
382  2022-01-20  us senate committee advances bill to tame big ...      0
705  2020-10-05            how walmart   s uk invasion fizzled out      0
814  2020-06-04                      snap makes trump posts vanish      1

In [21]:
# Assuming 'train' is your DataFrame containing the training dataset

# Create a list from the 'Title' column
headlines = train_df['Title'].tolist()

# Display the first few elements of the list
print(headlines[:5])  # Displaying the first 5 elements for example


['activist investor in peloton takes aim at new chief executive', 'apple and tesla turn spotlight back on stock splits', 'us senate committee advances bill to tame big tech   s power', 'how walmart   s uk invasion fizzled out', 'snap makes trump posts vanish']


In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier

In [23]:
countvector=CountVectorizer(ngram_range=(2,2))
traindataset=countvector.fit_transform(headlines)

In [24]:
traindataset[0]

<1x4610 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [25]:
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train_df['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [26]:
# Assuming you have already trained your model and defined countvector and randomclassifier

# Transform the 'Title' column of test data
test_transform = countvector.transform(test_df['Title'])

# Make predictions
predictions = randomclassifier.predict(test_transform)


In [ ]:
predictions

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1])

In [27]:
## Import library to check accuracy
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [28]:
matrix=confusion_matrix(test_df['Label'],predictions)
print(matrix)
score=accuracy_score(test_df['Label'],predictions)
print(score)
report=classification_report(test_df['Label'],predictions)
print(report)

[[ 8 87]
 [ 3 81]]
0.4972067039106145
              precision    recall  f1-score   support

           0       0.73      0.08      0.15        95
           1       0.48      0.96      0.64        84

    accuracy                           0.50       179
   macro avg       0.60      0.52      0.40       179
weighted avg       0.61      0.50      0.38       179



In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier

In [30]:
tfidfvector=TfidfVectorizer(ngram_range=(2,2))
traindataset=tfidfvector.fit_transform(headlines)

In [31]:
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(traindataset,train_df['Label'])

RandomForestClassifier(criterion='entropy', n_estimators=200)

In [32]:
# Assuming you have already trained your model and defined countvector and randomclassifier

# Transform the 'Title' column of test data
test_transform = tfidfvector.transform(test_df['Title'])

# Make predictions
predictions = randomclassifier.predict(test_transform)


In [33]:
matrix=confusion_matrix(test_df['Label'],predictions)
print(matrix)
score=accuracy_score(test_df['Label'],predictions)
print(score)
report=classification_report(test_df['Label'],predictions)
print(report)

[[ 9 86]
 [ 3 81]]
0.5027932960893855
              precision    recall  f1-score   support

           0       0.75      0.09      0.17        95
           1       0.49      0.96      0.65        84

    accuracy                           0.50       179
   macro avg       0.62      0.53      0.41       179
weighted avg       0.63      0.50      0.39       179



In [34]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
naive=MultinomialNB()
naive.fit(traindataset,train_df['Label'])

MultinomialNB()

In [36]:
# Assuming you have already trained your model and defined countvector and randomclassifier

# Transform the 'Title' column of test data
test_transform = tfidfvector.transform(test_df['Title'])

# Make predictions
predictions =naive.predict(test_transform)


In [37]:
matrix=confusion_matrix(test_df['Label'],predictions)
print(matrix)
score=accuracy_score(test_df['Label'],predictions)
print(score)
report=classification_report(test_df['Label'],predictions)
print(report)

[[25 70]
 [24 60]]
0.4748603351955307
              precision    recall  f1-score   support

           0       0.51      0.26      0.35        95
           1       0.46      0.71      0.56        84

    accuracy                           0.47       179
   macro avg       0.49      0.49      0.45       179
weighted avg       0.49      0.47      0.45       179

